spring:
  profiles:
    active: ${ENV:dev}
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: "${spring.profiles.active}"
        group: ORDER_SERVICE
  config:
    import:
      - nacos:order.yaml
      - nacos:database.yaml
      - nacos:resource_oauth.yaml?group=COMMON
      - nacos:nacos.yaml?group=COMMON
      - nacos:rocketmq.yaml?group=COMMON

order-id:
  worker-id: 1
  datacenter-id: 1

