spring:
  profiles:
    active: ${ENV:dev}
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: "${spring.profiles.active}"
        group: IAM_SERVICE
  config:
      import:
        - nacos:iam.yaml
        - nacos:database.yaml
        - nacos:oauth.yaml
        - nacos:nacos.yaml?group=COMMON





