spring:
  application:
    name: iam-service
  datasource:
    url: jdbc:mysql://localhost:3307/db_iam?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  authorization-server:
    # 配置JWT签发者URI，必须和授权服务器的地址一致
    issuer: http://localhost:10000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:10000
server:
  port: 10000

mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml # (可选) 使用XML文件
  global-config:
    db-config:
      id-type: auto # (可选) 主键自增
  configuration:  # 开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # (可选)

logging:
  level:
    com.hureru.iam.mapper: debug
    org.springframework.security: debug